name: Publish Docker image on every push to master branch

on:
  push:
    branches:
      - alpha
env:
  OTP_VERSION: "24.3.4.1"
  ELIXIR_VERSION: "1.13.4"
  NEXT_RELEASE_VERSION: 5.0.0

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.output-step.outputs.release-version }}
      short-sha: ${{ steps.output-step.outputs.short-sha }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_TOKEN }}

      - run: docker context create gha${{ github.sha }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/settlemint/blockscout-onprem

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Add outputs
        run: |
          echo "::set-output name=release-version::${{ env.NEXT_RELEASE_VERSION }}"
          echo "::set-output name=short-sha::${{ env.SHORT_SHA }}"
        id: output-step

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          cache-from: type=registry,ref=ghcr.io/settlemint/blockscout-onprem:buildcache
          cache-to: type=registry,ref=ghcr.io/settlemint/blockscout-onprem:buildcache,mode=max
          platforms: |
            linux/arm64
            linux/amd64
          tags: ghcr.io/settlemint/blockscout-onprem:latest, ghcr.io/settlemint/blockscout-onprem:${{ env.NEXT_RELEASE_VERSION }}-prerelease-${{ env.SHORT_SHA }}, ghcr.io/settlemint/blockscout-onprem:${{ env.NEXT_RELEASE_VERSION }}
          build-args: |
            CACHE_EXCHANGE_RATES_PERIOD=
            DISABLE_READ_API=false
            API_PATH=/insights
            NETWORK_PATH=/insights
            DISABLE_WEBAPP=false
            DISABLE_WRITE_API=false
            CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER=
            WOBSERVER_ENABLED=false
            ADMIN_PANEL_ENABLED=true
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            DISABLE_BRIDGE_MARKET_CAP_UPDATER=true
            CACHE_BRIDGE_MARKET_CAP_UPDATE_INTERVAL=
            SOCKET_ROOT=/
            CHAIN_ID=
            JSON_RPC=
            COIN_NAME=Native Token
            COIN=NT
            SUBNETWORK=
            DISABLE_EXCHANGE_RATES=true
            SECRET_KEY_BASE=RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5
            ENABLE_TXS_STATS=true
            SHOW_TXS_CHART=true
            LOGO=/explorer/images/blockscout_logo.svg
